//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAInteractionsUIModel
{

/// <summary>
/// Represents the UI model for the 'AIAAddConstituentInteractionPARTICIPANTS' data form
/// </summary>
public partial class @AIAAddConstituentInteractionPARTICIPANTSUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _constituentid;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIAAddConstituentInteractionPARTICIPANTSUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _constituentid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();

        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "ID";
        _id.Visible = false;
        this.Fields.Add(_id);
        //
        //_constituentid
        //
        _constituentid.Name = "CONSTITUENTID";
        _constituentid.Caption = "Participant";
        _constituentid.SearchListId = new System.Guid("23c5c603-d7d8-4106-aecc-65392b563887");
        _constituentid.EnableQuickFind = true;
        this.Fields.Add(_constituentid);

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

    /// <summary>
    /// Participant
    /// </summary>
    [System.ComponentModel.Description("Participant")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @CONSTITUENTID {
		get { return _constituentid; }
	}

}


}
