//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAInteractionsUIModel
{

/// <summary>
/// Represents the UI model for the 'Add constituent interaction (AIA)' data form
/// </summary>

public partial class @AIAAddConstituentInteractionUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the STATUSCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public enum STATUSCODES : int
	{
        @Pending = 1,
        @Completed = 2
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _interactiontypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _objective;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _fundraiserid;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _expecteddate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _expecteddaterelative;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _expecteddatedays;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _actualdate;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _actualdaterelative;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _actualdatedays;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<STATUSCODES> _statuscode;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _comment;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _eventid;
    private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionPARTICIPANTSUIModel> _participants;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactioncategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactionsubcategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionSITESUIModel> _sites;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _commentfieldgroup;
    private global::Blackbaud.AppFx.UIModeling.Core.GroupField _participantsfieldgroup;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _queryedit;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIAAddConstituentInteractionUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _interactiontypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _objective = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _fundraiserid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _expecteddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _expecteddaterelative = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _expecteddatedays = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _actualdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _actualdaterelative = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _actualdatedays = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _statuscode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<STATUSCODES>();
        _comment = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _eventid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _participants = new global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionPARTICIPANTSUIModel>();
        _interactioncategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _interactionsubcategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _sites = new global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionSITESUIModel>();
        _commentfieldgroup = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _participantsfieldgroup = new global::Blackbaud.AppFx.UIModeling.Core.GroupField();
        _queryedit = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        this.UserInterfaceUrl = "browser/htmlforms/custom/AIA/AIAAddConstituentInteraction.html";

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_interactiontypecodeid
        //
        _interactiontypecodeid.Name = "INTERACTIONTYPECODEID";
        _interactiontypecodeid.Caption = "Contact method";
        _interactiontypecodeid.Required = true;
        _interactiontypecodeid.CodeTableName = "INTERACTIONTYPECODE";
        this.Fields.Add(_interactiontypecodeid);
        //
        //_objective
        //
        _objective.Name = "OBJECTIVE";
        _objective.Caption = "Summary";
        _objective.Required = true;
        _objective.MaxLength = 100;
        this.Fields.Add(_objective);
        //
        //_fundraiserid
        //
        _fundraiserid.Name = "FUNDRAISERID";
        _fundraiserid.Caption = "Owner";
        _fundraiserid.SearchListId = new System.Guid("23c5c603-d7d8-4106-aecc-65392b563887");
        _fundraiserid.EnableQuickFind = true;
        _fundraiserid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "INCLUDEORGANIZATIONS", Caption = "Organizations", ReadOnly = true, DefaultValueText = "False"});
        _fundraiserid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "EXCLUDEHOUSEHOLDS", Caption = "EXCLUDEHOUSEHOLDS", Hidden = true, DefaultValueText = "True"});
        this.Fields.Add(_fundraiserid);
        //
        //_expecteddate
        //
        _expecteddate.Name = "EXPECTEDDATE";
        _expecteddate.Caption = "Expected date";
        _expecteddate.Required = true;
        this.Fields.Add(_expecteddate);
        //
        //_expecteddaterelative
        //
        _expecteddaterelative.Name = "EXPECTEDDATERELATIVE";
        _expecteddaterelative.Caption = "Relative date";
        this.Fields.Add(_expecteddaterelative);
        //
        //_expecteddatedays
        //
        _expecteddatedays.Name = "EXPECTEDDATEDAYS";
        _expecteddatedays.Caption = "Days from today";
        this.Fields.Add(_expecteddatedays);
        //
        //_actualdate
        //
        _actualdate.Name = "ACTUALDATE";
        _actualdate.Caption = "Actual date";
        this.Fields.Add(_actualdate);
        //
        //_actualdaterelative
        //
        _actualdaterelative.Name = "ACTUALDATERELATIVE";
        _actualdaterelative.Caption = "Relative date";
        this.Fields.Add(_actualdaterelative);
        //
        //_actualdatedays
        //
        _actualdatedays.Name = "ACTUALDATEDAYS";
        _actualdatedays.Caption = "Days from today";
        this.Fields.Add(_actualdatedays);
        //
        //_statuscode
        //
        _statuscode.Name = "STATUSCODE";
        _statuscode.Caption = "Status";
        _statuscode.Required = true;
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<STATUSCODES> {Value = STATUSCODES.@Pending, Translation = "Pending"});
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<STATUSCODES> {Value = STATUSCODES.@Completed, Translation = "Completed"});
        this.Fields.Add(_statuscode);
        //
        //_comment
        //
        _comment.Name = "COMMENT";
        _comment.Caption = "Comment";
        this.Fields.Add(_comment);
        //
        //_eventid
        //
        _eventid.Name = "EVENTID";
        _eventid.Caption = "Event";
        _eventid.SearchListId = new System.Guid("21452a39-7c7d-4334-8b89-6c0ea619acec");
        _eventid.EnableQuickFind = true;
        this.Fields.Add(_eventid);
        //
        //_participants
        //
        _participants.Name = "PARTICIPANTS";
        _participants.Caption = "Participants";
        this.Fields.Add(_participants);
        //
        //_interactioncategoryid
        //
        _interactioncategoryid.Name = "INTERACTIONCATEGORYID";
        _interactioncategoryid.Caption = "Category";
        _interactioncategoryid.SimpleDataListId = new System.Guid("cbba7545-b66f-44ac-aa24-d9c2f8cbc4ec");
        this.Fields.Add(_interactioncategoryid);
        //
        //_interactionsubcategoryid
        //
        _interactionsubcategoryid.Name = "INTERACTIONSUBCATEGORYID";
        _interactionsubcategoryid.Caption = "Subcategory";
        _interactionsubcategoryid.SimpleDataListId = new System.Guid("0eacc39b-07d1-4641-8774-e319559535a7");
        _interactionsubcategoryid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INTERACTIONCATEGORYID", "Fields!INTERACTIONCATEGORYID"));
        this.Fields.Add(_interactionsubcategoryid);
        //
        //_sites
        //
        _sites.Name = "SITES";
        _sites.Caption = "Interaction sites";
        this.Fields.Add(_sites);
        //
        //_commentfieldgroup
        //
        _commentfieldgroup.Name = "COMMENTFIELDGROUP";
        _commentfieldgroup.Caption = "Comment";
        _commentfieldgroup.Fields.Add("COMMENT");
        this.Fields.Add(_commentfieldgroup);
        //
        //_participantsfieldgroup
        //
        _participantsfieldgroup.Name = "PARTICIPANTSFIELDGROUP";
        _participantsfieldgroup.Caption = "Participants";
        _participantsfieldgroup.Fields.Add("PARTICIPANTS");
        this.Fields.Add(_participantsfieldgroup);
        //
        //_queryedit
        //
        _queryedit.Name = "QUERYEDIT";
        _queryedit.Caption = "";
        _idsetregisterid.LinkedActions.Add(_queryedit);
        this.Actions.Add(_queryedit);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Contact method
    /// </summary>
    [System.ComponentModel.Description("Contact method")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INTERACTIONTYPECODEID {
		get { return _interactiontypecodeid; }
	}

    /// <summary>
    /// Summary
    /// </summary>
    [System.ComponentModel.Description("Summary")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @OBJECTIVE {
		get { return _objective; }
	}

    /// <summary>
    /// Owner
    /// </summary>
    [System.ComponentModel.Description("Owner")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @FUNDRAISERID {
		get { return _fundraiserid; }
	}

    /// <summary>
    /// Expected date
    /// </summary>
    [System.ComponentModel.Description("Expected date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @EXPECTEDDATE {
		get { return _expecteddate; }
	}

    /// <summary>
    /// Relative date
    /// </summary>
    [System.ComponentModel.Description("Relative date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXPECTEDDATERELATIVE {
		get { return _expecteddaterelative; }
	}

    /// <summary>
    /// Days from today
    /// </summary>
    [System.ComponentModel.Description("Days from today")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @EXPECTEDDATEDAYS {
		get { return _expecteddatedays; }
	}

    /// <summary>
    /// Actual date
    /// </summary>
    [System.ComponentModel.Description("Actual date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ACTUALDATE {
		get { return _actualdate; }
	}

    /// <summary>
    /// Relative date
    /// </summary>
    [System.ComponentModel.Description("Relative date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @ACTUALDATERELATIVE {
		get { return _actualdaterelative; }
	}

    /// <summary>
    /// Days from today
    /// </summary>
    [System.ComponentModel.Description("Days from today")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @ACTUALDATEDAYS {
		get { return _actualdatedays; }
	}

    /// <summary>
    /// Status
    /// </summary>
    [System.ComponentModel.Description("Status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<STATUSCODES> @STATUSCODE {
		get { return _statuscode; }
	}

    /// <summary>
    /// Comment
    /// </summary>
    [System.ComponentModel.Description("Comment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COMMENT {
		get { return _comment; }
	}

    /// <summary>
    /// Event
    /// </summary>
    [System.ComponentModel.Description("Event")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @EVENTID {
		get { return _eventid; }
	}

    /// <summary>
    /// Participants
    /// </summary>
    [System.ComponentModel.Description("Participants")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionPARTICIPANTSUIModel> @PARTICIPANTS {
		get { return _participants; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONCATEGORYID {
		get { return _interactioncategoryid; }
	}

    /// <summary>
    /// Subcategory
    /// </summary>
    [System.ComponentModel.Description("Subcategory")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONSUBCATEGORYID {
		get { return _interactionsubcategoryid; }
	}

    /// <summary>
    /// Interaction sites
    /// </summary>
    [System.ComponentModel.Description("Interaction sites")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIAAddConstituentInteractionSITESUIModel> @SITES {
		get { return _sites; }
	}

    /// <summary>
    /// Comment
    /// </summary>
    [System.ComponentModel.Description("Comment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @COMMENTFIELDGROUP {
		get { return _commentfieldgroup; }
	}

    /// <summary>
    /// Participants
    /// </summary>
    [System.ComponentModel.Description("Participants")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GroupField @PARTICIPANTSFIELDGROUP {
		get { return _participantsfieldgroup; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @QUERYEDIT {
		get { return _queryedit; }
	}

}

}
