//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAInteractionsUIModel
{

/// <summary>
/// Represents the UI model for the 'Delete interaction attribute (AIA)' data form
/// </summary>

public partial class @AIADeleteInteractionAttributeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the DELETETYPE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public enum DELETETYPES : int
	{
        @DeleteAllValues = 0,
        @DeleteOnlyAttributesWithTheValue = 1
	}

    /// <summary>
    /// Enumerated values for use with the BOOLEANVALUE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public enum BOOLEANVALUES : int
	{
        @No = 0,
        @Yes = 1
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _attributecategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<DELETETYPES>> _deletetype;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _stringvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _numbervalue;
    private global::Blackbaud.AppFx.UIModeling.Core.MoneyField _moneyvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _datevalue;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<BOOLEANVALUES>> _booleanvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _codetablevalue;
    private global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField _fuzzydatevalue;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _constituentidvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField _hourminutevalue;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _memovalue;
    private global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIADeleteInteractionAttributeATTRIBUTECATEGORIESUIModel> _attributecategories;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _currencyid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _queryedit;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIADeleteInteractionAttributeUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _attributecategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _deletetype = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<DELETETYPES>>();
        _stringvalue = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _numbervalue = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _moneyvalue = new global::Blackbaud.AppFx.UIModeling.Core.MoneyField();
        _datevalue = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _booleanvalue = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<BOOLEANVALUES>>();
        _codetablevalue = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _fuzzydatevalue = new global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField();
        _constituentidvalue = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _hourminutevalue = new global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField();
        _memovalue = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _attributecategories = new global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIADeleteInteractionAttributeATTRIBUTECATEGORIESUIModel>();
        _currencyid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _queryedit = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        this.UserInterfaceUrl = "browser/htmlforms/custom/AIA/AIADeleteInteractionAttribute.html";

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_attributecategoryid
        //
        _attributecategoryid.Name = "ATTRIBUTECATEGORYID";
        _attributecategoryid.Caption = "Category";
        _attributecategoryid.Required = true;
        _attributecategoryid.SimpleDataListId = new System.Guid("958132a3-762a-4844-b7a1-f3a3098da95a");
        _attributecategoryid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("RECORDTYPE", "Interaction"));
        this.Fields.Add(_attributecategoryid);
        //
        //_deletetype
        //
        _deletetype.Name = "DELETETYPE";
        _deletetype.Caption = "Delete type";
        _deletetype.Description = "Radio buttons for choosing which style of delete to use.";
        _deletetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<DELETETYPES>> {Value = DELETETYPES.@DeleteAllValues, Translation = "Delete all values"});
        _deletetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<DELETETYPES>> {Value = DELETETYPES.@DeleteOnlyAttributesWithTheValue, Translation = "Delete only attributes with the value:"});
        _deletetype.Value = DELETETYPES.@DeleteAllValues;
        this.Fields.Add(_deletetype);
        //
        //_stringvalue
        //
        _stringvalue.Name = "STRINGVALUE";
        _stringvalue.Caption = "Value";
        _stringvalue.MaxLength = 250;
        this.Fields.Add(_stringvalue);
        //
        //_numbervalue
        //
        _numbervalue.Name = "NUMBERVALUE";
        _numbervalue.Caption = "Value";
        this.Fields.Add(_numbervalue);
        //
        //_moneyvalue
        //
        _moneyvalue.Name = "MONEYVALUE";
        _moneyvalue.Caption = "Value";
        _moneyvalue.CurrencyFieldId = "CURRENCYID";
        this.Fields.Add(_moneyvalue);
        //
        //_datevalue
        //
        _datevalue.Name = "DATEVALUE";
        _datevalue.Caption = "Value";
        this.Fields.Add(_datevalue);
        //
        //_booleanvalue
        //
        _booleanvalue.Name = "BOOLEANVALUE";
        _booleanvalue.Caption = "Value";
        _booleanvalue.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<BOOLEANVALUES>> {Value = BOOLEANVALUES.@No, Translation = "No"});
        _booleanvalue.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<BOOLEANVALUES>> {Value = BOOLEANVALUES.@Yes, Translation = "Yes"});
        this.Fields.Add(_booleanvalue);
        //
        //_codetablevalue
        //
        _codetablevalue.Name = "CODETABLEVALUE";
        _codetablevalue.Caption = "Value";
        _codetablevalue.CodeTableName = "ADDRESSTYPECODE";
        this.Fields.Add(_codetablevalue);
        //
        //_fuzzydatevalue
        //
        _fuzzydatevalue.Name = "FUZZYDATEVALUE";
        _fuzzydatevalue.Caption = "Value";
        this.Fields.Add(_fuzzydatevalue);
        //
        //_constituentidvalue
        //
        _constituentidvalue.Name = "CONSTITUENTIDVALUE";
        _constituentidvalue.Caption = "Value";
        _constituentidvalue.SearchListId = new System.Guid("23c5c603-d7d8-4106-aecc-65392b563887");
        _constituentidvalue.EnableQuickFind = true;
        _constituentidvalue.SearchListAddForms.Add(new global::Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(new System.Guid("1986f0cf-efb6-48b3-afde-950b57562434"), "Individual"));
        _constituentidvalue.SearchListAddForms.Add(new global::Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(new System.Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"));
        _constituentidvalue.SearchListAddForms.Add(new global::Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(new System.Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"));
        _constituentidvalue.SearchListAddForms.Add(new global::Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(new System.Guid("ca3ed110-a5f0-4b5b-8eb7-0616e0a82e8e"), "Organization"));
        this.Fields.Add(_constituentidvalue);
        //
        //_hourminutevalue
        //
        _hourminutevalue.Name = "HOURMINUTEVALUE";
        _hourminutevalue.Caption = "Value";
        this.Fields.Add(_hourminutevalue);
        //
        //_memovalue
        //
        _memovalue.Name = "MEMOVALUE";
        _memovalue.Caption = "Value";
        this.Fields.Add(_memovalue);
        //
        //_attributecategories
        //
        _attributecategories.Name = "ATTRIBUTECATEGORIES";
        _attributecategories.Caption = "ATTRIBUTECATEGORIES";
        _attributecategories.DBReadOnly = true;
        _attributecategories.AvailableToClient = false;
        this.Fields.Add(_attributecategories);
        //
        //_currencyid
        //
        _currencyid.Name = "CURRENCYID";
        _currencyid.Caption = "Currency";
        _currencyid.SimpleDataListId = new System.Guid("13612288-b37e-409d-ba52-6ab31637ddd6");
        this.Fields.Add(_currencyid);
        //
        //_queryedit
        //
        _queryedit.Name = "QUERYEDIT";
        _queryedit.Caption = "";
        _idsetregisterid.LinkedActions.Add(_queryedit);
        this.Actions.Add(_queryedit);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @ATTRIBUTECATEGORYID {
		get { return _attributecategoryid; }
	}

    /// <summary>
    /// Radio buttons for choosing which style of delete to use.
    /// </summary>
    [System.ComponentModel.Description("Radio buttons for choosing which style of delete to use.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<DELETETYPES>> @DELETETYPE {
		get { return _deletetype; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @STRINGVALUE {
		get { return _stringvalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @NUMBERVALUE {
		get { return _numbervalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.MoneyField @MONEYVALUE {
		get { return _moneyvalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @DATEVALUE {
		get { return _datevalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<BOOLEANVALUES>> @BOOLEANVALUE {
		get { return _booleanvalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @CODETABLEVALUE {
		get { return _codetablevalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.FuzzyDateField @FUZZYDATEVALUE {
		get { return _fuzzydatevalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @CONSTITUENTIDVALUE {
		get { return _constituentidvalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.HourMinuteField @HOURMINUTEVALUE {
		get { return _hourminutevalue; }
	}

    /// <summary>
    /// Value
    /// </summary>
    [System.ComponentModel.Description("Value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @MEMOVALUE {
		get { return _memovalue; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CollectionField<AIADeleteInteractionAttributeATTRIBUTECATEGORIESUIModel> @ATTRIBUTECATEGORIES {
		get { return _attributecategories; }
	}

    /// <summary>
    /// Currency
    /// </summary>
    [System.ComponentModel.Description("Currency")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @CURRENCYID {
		get { return _currencyid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @QUERYEDIT {
		get { return _queryedit; }
	}

}

}
