//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAInteractionsUIModel
{

/// <summary>
/// Represents the UI model for the 'AIADeleteInteractionAttributeATTRIBUTECATEGORIES' data form
/// </summary>
public partial class @AIADeleteInteractionAttributeATTRIBUTECATEGORIESUIModel : global::Blackbaud.AppFx.UIModeling.Core.UIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _id;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _datatypecode;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _constituentsearchlistcatalogid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _codetablename;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIADeleteInteractionAttributeATTRIBUTECATEGORIESUIModel() : base()
	{


        _id = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _datatypecode = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _constituentsearchlistcatalogid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _codetablename = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        //
        //_id
        //
        _id.Name = "ID";
        _id.Caption = "ID";
        this.Fields.Add(_id);
        //
        //_datatypecode
        //
        _datatypecode.Name = "DATATYPECODE";
        _datatypecode.Caption = "DATATYPECODE";
        this.Fields.Add(_datatypecode);
        //
        //_constituentsearchlistcatalogid
        //
        _constituentsearchlistcatalogid.Name = "CONSTITUENTSEARCHLISTCATALOGID";
        _constituentsearchlistcatalogid.Caption = "CONSTITUENTSEARCHLISTCATALOGID";
        this.Fields.Add(_constituentsearchlistcatalogid);
        //
        //_codetablename
        //
        _codetablename.Name = "CODETABLENAME";
        _codetablename.Caption = "CODETABLENAME";
        this.Fields.Add(_codetablename);

		OnCreated();

	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @ID {
		get { return _id; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @DATATYPECODE {
		get { return _datatypecode; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @CONSTITUENTSEARCHLISTCATALOGID {
		get { return _constituentsearchlistcatalogid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @CODETABLENAME {
		get { return _codetablename; }
	}

}


}
