//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAInteractionsUIModel
{

/// <summary>
/// Represents the UI model for the 'Interaction dates (AIA)' data form
/// </summary>

public partial class @AIAInteractionDatesUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the STATUSCODE property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public enum STATUSCODES : int
	{
        @Pending = 1,
        @Completed = 2,
        @Canceled = 4,
        @Declined = 5
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string> _datefield;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string> _datetype;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<STATUSCODES>> _statuscode;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _actualstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _actualenddate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _plannedstartdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _plannedenddate;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _owner;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _interactiontypecodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactioncategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _interactionsubcategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _queryedit;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIAInteractionDatesUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _datefield = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string>();
        _datetype = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string>();
        _statuscode = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<STATUSCODES>>();
        _actualstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _actualenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _plannedstartdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _plannedenddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _owner = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _interactiontypecodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _interactioncategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _interactionsubcategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _queryedit = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        this.UserInterfaceUrl = "browser/htmlforms/custom/AIA/AIAInteractionDates.html";

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_datefield
        //
        _datefield.Name = "DATEFIELD";
        _datefield.Caption = "Date field to return";
        _datefield.Required = true;
        _datefield.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<string> {Value = "DATE", Translation = "Date"});
        _datefield.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<string> {Value = "ACTUALDATE", Translation = "Actual Date"});
        _datefield.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<string> {Value = "EXPECTEDDATE", Translation = "Expected Date"});
        this.Fields.Add(_datefield);
        //
        //_datetype
        //
        _datetype.Name = "DATETYPE";
        _datetype.Caption = "Value to return";
        _datetype.Required = true;
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<string> {Value = "MIN", Translation = "Earliest date"});
        _datetype.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<string> {Value = "MAX", Translation = "Latest date"});
        this.Fields.Add(_datetype);
        //
        //_statuscode
        //
        _statuscode.Name = "STATUSCODE";
        _statuscode.Caption = "Status";
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<STATUSCODES>> {Value = STATUSCODES.@Pending, Translation = "Pending"});
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<STATUSCODES>> {Value = STATUSCODES.@Completed, Translation = "Completed"});
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<STATUSCODES>> {Value = STATUSCODES.@Canceled, Translation = "Canceled"});
        _statuscode.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<System.Nullable<STATUSCODES>> {Value = STATUSCODES.@Declined, Translation = "Declined"});
        this.Fields.Add(_statuscode);
        //
        //_actualstartdate
        //
        _actualstartdate.Name = "ACTUALSTARTDATE";
        _actualstartdate.Caption = "Actual date from";
        this.Fields.Add(_actualstartdate);
        //
        //_actualenddate
        //
        _actualenddate.Name = "ACTUALENDDATE";
        _actualenddate.Caption = "Actual date to";
        this.Fields.Add(_actualenddate);
        //
        //_plannedstartdate
        //
        _plannedstartdate.Name = "PLANNEDSTARTDATE";
        _plannedstartdate.Caption = "Expected date from";
        this.Fields.Add(_plannedstartdate);
        //
        //_plannedenddate
        //
        _plannedenddate.Name = "PLANNEDENDDATE";
        _plannedenddate.Caption = "Expected date to";
        this.Fields.Add(_plannedenddate);
        //
        //_owner
        //
        _owner.Name = "OWNER";
        _owner.Caption = "Owner";
        _owner.SearchListId = new System.Guid("23c5c603-d7d8-4106-aecc-65392b563887");
        _owner.EnableQuickFind = true;
        _owner.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "INCLUDEORGANIZATIONS", Caption = "Organizations", ReadOnly = true, DefaultValueText = "False"});
        _owner.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "EXCLUDEHOUSEHOLDS", Caption = "EXCLUDEHOUSEHOLDS", Hidden = true, DefaultValueText = "True"});
        _owner.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "INCLUDENONCONSTITUENTRECORDS", DefaultValueText = "true"});
        _owner.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "FORMHEADER", DefaultValueText = "Record Search"});
        this.Fields.Add(_owner);
        //
        //_interactiontypecodeid
        //
        _interactiontypecodeid.Name = "INTERACTIONTYPECODEID";
        _interactiontypecodeid.Caption = "Contact method";
        _interactiontypecodeid.CodeTableName = "INTERACTIONTYPECODE";
        this.Fields.Add(_interactiontypecodeid);
        //
        //_interactioncategoryid
        //
        _interactioncategoryid.Name = "INTERACTIONCATEGORYID";
        _interactioncategoryid.Caption = "Category";
        _interactioncategoryid.SimpleDataListId = new System.Guid("cbba7545-b66f-44ac-aa24-d9c2f8cbc4ec");
        this.Fields.Add(_interactioncategoryid);
        //
        //_interactionsubcategoryid
        //
        _interactionsubcategoryid.Name = "INTERACTIONSUBCATEGORYID";
        _interactionsubcategoryid.Caption = "Subcategory";
        _interactionsubcategoryid.SimpleDataListId = new System.Guid("0eacc39b-07d1-4641-8774-e319559535a7");
        _interactionsubcategoryid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("INTERACTIONCATEGORYID", "Fields!INTERACTIONCATEGORYID"));
        this.Fields.Add(_interactionsubcategoryid);
        //
        //_queryedit
        //
        _queryedit.Name = "QUERYEDIT";
        _queryedit.Caption = "";
        _idsetregisterid.LinkedActions.Add(_queryedit);
        this.Actions.Add(_queryedit);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Date field to return
    /// </summary>
    [System.ComponentModel.Description("Date field to return")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string> @DATEFIELD {
		get { return _datefield; }
	}

    /// <summary>
    /// Value to return
    /// </summary>
    [System.ComponentModel.Description("Value to return")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<string> @DATETYPE {
		get { return _datetype; }
	}

    /// <summary>
    /// Status
    /// </summary>
    [System.ComponentModel.Description("Status")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<System.Nullable<STATUSCODES>> @STATUSCODE {
		get { return _statuscode; }
	}

    /// <summary>
    /// Actual date from
    /// </summary>
    [System.ComponentModel.Description("Actual date from")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ACTUALSTARTDATE {
		get { return _actualstartdate; }
	}

    /// <summary>
    /// Actual date to
    /// </summary>
    [System.ComponentModel.Description("Actual date to")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ACTUALENDDATE {
		get { return _actualenddate; }
	}

    /// <summary>
    /// Expected date from
    /// </summary>
    [System.ComponentModel.Description("Expected date from")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @PLANNEDSTARTDATE {
		get { return _plannedstartdate; }
	}

    /// <summary>
    /// Expected date to
    /// </summary>
    [System.ComponentModel.Description("Expected date to")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @PLANNEDENDDATE {
		get { return _plannedenddate; }
	}

    /// <summary>
    /// Owner
    /// </summary>
    [System.ComponentModel.Description("Owner")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @OWNER {
		get { return _owner; }
	}

    /// <summary>
    /// Contact method
    /// </summary>
    [System.ComponentModel.Description("Contact method")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @INTERACTIONTYPECODEID {
		get { return _interactiontypecodeid; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONCATEGORYID {
		get { return _interactioncategoryid; }
	}

    /// <summary>
    /// Subcategory
    /// </summary>
    [System.ComponentModel.Description("Subcategory")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @INTERACTIONSUBCATEGORYID {
		get { return _interactionsubcategoryid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @QUERYEDIT {
		get { return _queryedit; }
	}

}

}
